source 'https://rubygems.org'

gem 'rails', github: "rails/rails"

# Use postgresql as the database for Active Record
gem 'pg'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.0'
# Use Puma as the app server
gem 'puma'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# Add bcrypt
gem 'bcrypt'

# Add serializers
gem "active_model_serializers", github: "rails-api/active_model_serializers"

# Add dalli for sessions
#gem 'dalli'

# Add jwt
gem 'jwt'

# Add pagination
gem 'kaminari'
#gem 'api_pagination_headers'

# mail
gem 'mailgun-ruby', require: 'mailgun'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'faker'
  gem 'factory_girl'
  gem 'rack-test'
end

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :production do
  gem 'unicorn'
  gem 'faker'
  gem 'factory_girl'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
